# Generated by Django 4.1.10 on 2023-07-10 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_users_groups_users_is_superuser_users_last_login_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="users", name="groups",),
        migrations.RemoveField(model_name="users", name="is_superuser",),
        migrations.RemoveField(model_name="users", name="user_permissions",),
    ]
