# Generated by Django 4.0.10 on 2023-07-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
